source /home/cad5/Hw-2/sel_sense_hs_c.tcl
rm designs/*
source /home/cad5/Hw-2/sel_sense_ms_c.tcl
rm designs/*
source /home/cad5/Hw-2/sel_sense_hs_d.tcl
rm designs/*
source /home/cad5/Hw-2/sel_sense_ms_d.tcl
rm designs/*
source /home/cad5/Hw-2/sel_sense_hs_6.tcl
rm designs/*
source /home/cad5/Hw-2/sel_sense_ms_6.tcl
rm designs/*
source /home/cad5/Hw-2/mux_comparator_c_OCL.tcl
rm designs/*
source /home/cad5/Hw-2/mux_comparator_c_RAK.tcl
rm designs/*
source /home/cad5/Hw-2/mux_comparator_8bit_RAK.tcl
rm designs/*

