
// Generated by Cadence Genus(TM) Synthesis Solution 16.25-s068_1
// Generated on: Sep 26 2021 12:42:36 IST (Sep 26 2021 07:12:36 UTC)

// Verification Directory fv/mux_comparator 

module mux_comparator(x, y, z);
  input [2:0] x, y;
  output [2:0] z;
  wire [2:0] x, y;
  wire [2:0] z;
  wire n_28, n_60, n_86, n_87, n_88, n_89, n_93, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_105, n_106, n_107;
  wire n_108, n_111, n_112, n_118;
  INVXL g185(.A (y[0]), .Y (n_28));
  AND2X6 g194(.A (x[2]), .B (y[2]), .Y (z[2]));
  OAI21XL g1067(.A0 (n_88), .A1 (n_89), .B0 (n_118), .Y (z[1]));
  NOR2X6 g1070(.A (y[1]), .B (n_87), .Y (n_88));
  NOR2X8 g1073(.A (x[2]), .B (n_86), .Y (n_87));
  INVX20 g1079(.A (y[2]), .Y (n_86));
  INVX20 g1080(.A (x[1]), .Y (n_89));
  NOR2X8 g1076(.A (x[0]), .B (x[1]), .Y (n_93));
  AOI21X4 g1069(.A0 (n_97), .A1 (n_99), .B0 (n_101), .Y (n_102));
  NOR2X8 g1074(.A (n_89), .B (n_60), .Y (n_97));
  INVX20 g1078(.A (x[0]), .Y (n_60));
  NAND2X8 g1072(.A (y[2]), .B (n_98), .Y (n_99));
  INVX20 g1081_dup(.A (x[2]), .Y (n_98));
  NOR2X2 g1077(.A (y[2]), .B (n_100), .Y (n_101));
  INVX4 g1081(.A (x[2]), .Y (n_100));
  NAND2X2 g92(.A (n_105), .B (n_102), .Y (n_106));
  INVX2 g95(.A (n_60), .Y (n_105));
  NOR2X4 g91(.A (n_112), .B (n_107), .Y (n_108));
  INVX3 g93(.A (n_102), .Y (n_107));
  OAI22X2 g33(.A0 (n_112), .A1 (n_106), .B0 (n_28), .B1 (n_108), .Y
       (z[0]));
  NOR2X8 g34(.A (n_93), .B (n_111), .Y (n_112));
  INVX8 g36(.A (n_88), .Y (n_111));
  NAND3BX4 g2(.AN (y[2]), .B (y[1]), .C (x[2]), .Y (n_118));
endmodule

