
// Generated by Cadence Genus(TM) Synthesis Solution 16.25-s068_1
// Generated on: Sep 26 2021 12:42:32 IST (Sep 26 2021 07:12:32 UTC)

// Verification Directory fv/mux_comparator 

module mux_comparator(x, y, z);
  input [2:0] x, y;
  output [2:0] z;
  wire [2:0] x, y;
  wire [2:0] z;
  wire n_156, n_231, n_292, n_296, n_297, n_298, n_305, n_306;
  wire n_307, n_313, n_314, n_315, n_318, n_320, n_321, n_322;
  wire n_340, n_341, n_348, n_349, n_350, n_368, n_369, n_370;
  wire n_371, n_372, n_373, n_374, n_375, n_376;
  NOR2_X1 g4857(.A1 (n_374), .A2 (y[1]), .ZN (n_156));
  INV_X2 g96(.I (y[1]), .ZN (n_231));
  OAI21_X1 g23(.A1 (n_348), .A2 (n_318), .B (n_341), .ZN (z[1]));
  OAI21_X1 g106(.A1 (n_231), .A2 (x[0]), .B (x[2]), .ZN (n_292));
  NAND2_X2 g103(.A1 (n_297), .A2 (n_370), .ZN (n_298));
  OAI21_X2 g272(.A1 (n_296), .A2 (x[1]), .B (x[0]), .ZN (n_297));
  INV_X4 g108(.I (y[1]), .ZN (n_296));
  OAI21_X2 g276(.A1 (x[0]), .A2 (x[1]), .B (n_368), .ZN (n_305));
  NOR2_X2 g71(.A1 (n_374), .A2 (n_373), .ZN (n_306));
  INV_X4 g72(.I (y[2]), .ZN (n_307));
  NAND2_X1 g70(.A1 (n_307), .A2 (x[2]), .ZN (n_313));
  NOR2_X1 g36(.A1 (n_314), .A2 (n_315), .ZN (z[2]));
  NOR2_X1 g38(.A1 (n_298), .A2 (n_156), .ZN (n_314));
  NAND2_X1 g37(.A1 (x[2]), .A2 (y[2]), .ZN (n_315));
  OAI21_X1 g35(.A1 (n_298), .A2 (n_156), .B (y[1]), .ZN (n_318));
  NAND2_X1 g227(.A1 (n_322), .A2 (n_349), .ZN (z[0]));
  OAI21_X1 g228(.A1 (n_350), .A2 (n_321), .B (y[0]), .ZN (n_322));
  INV_X1 g230(.I (n_320), .ZN (n_321));
  OAI21_X2 g231(.A1 (n_306), .A2 (x[2]), .B (n_307), .ZN (n_320));
  NAND4_X1 g82(.A1 (n_369), .A2 (n_292), .A3 (n_340), .A4 (n_313), .ZN
       (n_341));
  NOR2_X1 g83(.A1 (n_368), .A2 (n_374), .ZN (n_340));
  AND2_X1 g46(.A1 (n_376), .A2 (y[2]), .Z (n_348));
  NAND4_X1 g45(.A1 (n_320), .A2 (n_376), .A3 (n_305), .A4 (x[0]), .ZN
       (n_349));
  NAND2_X1 g47(.A1 (n_376), .A2 (n_305), .ZN (n_350));
  NOR2_X2 g289(.A1 (y[1]), .A2 (y[2]), .ZN (n_368));
  OR3_X1 g2(.A1 (n_373), .A2 (n_374), .A3 (y[2]), .Z (n_369));
  NAND2_X2 g94(.A1 (n_372), .A2 (n_375), .ZN (n_376));
  NOR2_X2 g290(.A1 (n_370), .A2 (n_371), .ZN (n_372));
  INV_X4 g291(.I (x[2]), .ZN (n_370));
  NOR2_X2 g292(.A1 (x[1]), .A2 (x[0]), .ZN (n_371));
  OAI21_X2 g293(.A1 (n_373), .A2 (n_374), .B (y[1]), .ZN (n_375));
  INV_X8 g98(.I (x[0]), .ZN (n_373));
  INV_X16 g294(.I (x[1]), .ZN (n_374));
endmodule

