
// Generated by Cadence Genus(TM) Synthesis Solution 16.25-s068_1
// Generated on: Sep 26 2021 12:42:17 IST (Sep 26 2021 07:12:17 UTC)

// Verification Directory fv/sel_sense 

module sel_sense(A, S, B);
  input A, S;
  output B;
  wire A, S;
  wire B;
  sky130_fd_sc_hs__xor2_1 g14__7837(.A (S), .B (A), .X (B));
endmodule

