
// Generated by Cadence Genus(TM) Synthesis Solution 16.25-s068_1
// Generated on: Sep 26 2021 12:42:19 IST (Sep 26 2021 07:12:19 UTC)

// Verification Directory fv/sel_sense 

module sel_sense(A, S, B);
  input A, S;
  output B;
  wire A, S;
  wire B;
  wire n_13, n_14, n_15, n_16;
  sky130_fd_sc_hs__nand2_1 g16(.A (n_14), .B (n_16), .Y (B));
  sky130_fd_sc_hs__nand2_2 g20(.A (n_13), .B (S), .Y (n_14));
  sky130_fd_sc_hs__inv_8 g21(.A (A), .Y (n_13));
  sky130_fd_sc_hs__nand2_2 g17(.A (n_15), .B (A), .Y (n_16));
  sky130_fd_sc_hs__inv_16 g19(.A (S), .Y (n_15));
endmodule

